spring:
  devtools:
    livereload:
      enabled: true

cloud:
  aws:
    s3:
      bucket: ask-springboot-build
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true